### ISSUE TITLE
Mysql2::Error: All parts of a PRIMARY KEY must be NOT NULL;

### ISSUE THREAD

**Issue by rocknrollMarc** [AlchemyCMS/alchemy-spree-demo#4]
Mysql2::Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead: CREATE TABLE `alchemy_attachments` (`id` int(11) DEFAULT NULL auto_increment PRIMARY KEY, `name` varchar(255), `file_name` varchar(255), `file_mime_type` varchar(255), `file_size` int(11), `creator_id` int(11), `updater_id` int(11), `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `cached_tag_list` text, `file_uid` varchar(255)) ENGINE=InnoDB/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activesupport-3.2.15/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `execute'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/connection_adapters/mysql2_adapter.rb:213:in `execute'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/connection_adapters/abstract/schema_statements.rb:170:in `create_table'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:434:in `create_table'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/migration.rb:466:in `block in method_missing'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/migration.rb:438:in `block in say_with_time'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/migration.rb:438:in `say_with_time'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/migration.rb:458:in `method_missing'
/Users/marc/workspace/rails/spree_ecomerce/alchemy-spree-demo/db/migrate/20131029130906_alchemy_two_point_six.alchemy.rb:14:in `up'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/migration.rb:410:in `block in migrate'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/activerecord-3.2.15/lib/active_record/connection_adapters/abstract/co

**Comment by rocknrollMarc** [comment]
I fixed it you have to add an intializer:

config/initializers/abstract_mysql_adapter.rb

class ActiveRecord::ConnectionAdapters::Mysql2Adapter
    NATIVE_DATABASE_TYPES[:primary_key] = "int(11) auto_increment PRIMARY KEY"
end

I also downgraded mysql to 5.6

THis also workes for the Error:

There was an error while trying to load the gem 'mysql2'.
Gem Load Error is: uninitialized constant Mysql2::Client::SECURE_CONNECTION
Backtrace for gem load error is:
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/mysql2-0.3.14/lib/mysql2/client.rb:12:in `<class:Client>'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/mysql2-0.3.14/lib/mysql2/client.rb:2:in `<module:Mysql2>'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/mysql2-0.3.14/lib/mysql2/client.rb:1:in `<top (required)>'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/mysql2-0.3.14/lib/mysql2.rb:10:in `require'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/mysql2-0.3.14/lib/mysql2.rb:10:in `<top (required)>'
/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/bundler-1.13.1/lib/bundler/runtime.rb:91:in `require'

Ill open a new Issue for that just for documentation purpose.
